SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `huwikiquote_actor_log_stats_by_type_action`;
TRUNCATE TABLE `huwikiquote_log_stats_by_type_action`;
TRUNCATE TABLE `huwikiquote_actor_log_stats_by_action`;
TRUNCATE TABLE `huwikiquote_log_stats_by_action`;
TRUNCATE TABLE `huwikiquote_actor_log_stats_by_type`;
TRUNCATE TABLE `huwikiquote_log_stats_by_type`;
TRUNCATE TABLE `huwikiquote_actor_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwikiquote_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwikiquote_actor_edit_stats_by_tag`;
TRUNCATE TABLE `huwikiquote_edit_stats_by_tag`;
TRUNCATE TABLE `huwikiquote_actor_daily_stats_by_ns`;
TRUNCATE TABLE `huwikiquote_daily_stats_by_ns`;
TRUNCATE TABLE `huwikiquote_actor_daily_stats`;
TRUNCATE TABLE `huwikiquote_daily_stats`;
TRUNCATE TABLE `huwikiquote_actor_groups`;
TRUNCATE TABLE `huwikiquote_actor`;
SET FOREIGN_KEY_CHECKS = 1;
