SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `huwikisource_actor_log_stats_by_type_action`;
TRUNCATE TABLE `huwikisource_log_stats_by_type_action`;
TRUNCATE TABLE `huwikisource_actor_log_stats_by_action`;
TRUNCATE TABLE `huwikisource_log_stats_by_action`;
TRUNCATE TABLE `huwikisource_actor_log_stats_by_type`;
TRUNCATE TABLE `huwikisource_log_stats_by_type`;
TRUNCATE TABLE `huwikisource_actor_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwikisource_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwikisource_actor_edit_stats_by_tag`;
TRUNCATE TABLE `huwikisource_edit_stats_by_tag`;
TRUNCATE TABLE `huwikisource_actor_daily_stats_by_ns`;
TRUNCATE TABLE `huwikisource_daily_stats_by_ns`;
TRUNCATE TABLE `huwikisource_actor_daily_stats`;
TRUNCATE TABLE `huwikisource_daily_stats`;
TRUNCATE TABLE `huwikisource_actor_groups`;
TRUNCATE TABLE `huwikisource_actor`;
SET FOREIGN_KEY_CHECKS = 1;
