SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `huwiki_actor_log_stats_by_type_action`;
TRUNCATE TABLE `huwiki_log_stats_by_type_action`;
TRUNCATE TABLE `huwiki_actor_log_stats_by_action`;
TRUNCATE TABLE `huwiki_log_stats_by_action`;
TRUNCATE TABLE `huwiki_actor_log_stats_by_type`;
TRUNCATE TABLE `huwiki_log_stats_by_type`;
TRUNCATE TABLE `huwiki_actor_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwiki_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwiki_actor_edit_stats_by_tag`;
TRUNCATE TABLE `huwiki_edit_stats_by_tag`;
TRUNCATE TABLE `huwiki_actor_daily_stats_by_ns`;
TRUNCATE TABLE `huwiki_daily_stats_by_ns`;
TRUNCATE TABLE `huwiki_actor_daily_stats`;
TRUNCATE TABLE `huwiki_daily_stats`;
TRUNCATE TABLE `huwiki_actor_groups`;
TRUNCATE TABLE `huwiki_actor`;
SET FOREIGN_KEY_CHECKS = 1;
