SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `huwiktionary_actor_log_stats_by_type_action`;
TRUNCATE TABLE `huwiktionary_log_stats_by_type_action`;
TRUNCATE TABLE `huwiktionary_actor_log_stats_by_action`;
TRUNCATE TABLE `huwiktionary_log_stats_by_action`;
TRUNCATE TABLE `huwiktionary_actor_log_stats_by_type`;
TRUNCATE TABLE `huwiktionary_log_stats_by_type`;
TRUNCATE TABLE `huwiktionary_actor_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwiktionary_edit_stats_by_ns_tag`;
TRUNCATE TABLE `huwiktionary_actor_edit_stats_by_tag`;
TRUNCATE TABLE `huwiktionary_edit_stats_by_tag`;
TRUNCATE TABLE `huwiktionary_actor_daily_stats_by_ns`;
TRUNCATE TABLE `huwiktionary_daily_stats_by_ns`;
TRUNCATE TABLE `huwiktionary_actor_daily_stats`;
TRUNCATE TABLE `huwiktionary_daily_stats`;
TRUNCATE TABLE `huwiktionary_actor_groups`;
TRUNCATE TABLE `huwiktionary_actor`;
SET FOREIGN_KEY_CHECKS = 1;
