SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `huwiktionary_actor_log_stats_by_nslt_v2`;
TRUNCATE TABLE `huwiktionary_actor_log_stats_v2`;
TRUNCATE TABLE `huwiktionary_actor_edit_stats_by_ns_v2`;
TRUNCATE TABLE `huwiktionary_actor_edit_stats_v2`;
TRUNCATE TABLE `huwiktionary_actor_groups_v2`;
TRUNCATE TABLE `huwiktionary_actor_v2`;
TRUNCATE TABLE `huwikiquote_actor_log_stats_by_nslt_v2`;
TRUNCATE TABLE `huwikiquote_actor_log_stats_v2`;
TRUNCATE TABLE `huwikiquote_actor_edit_stats_by_ns_v2`;
TRUNCATE TABLE `huwikiquote_actor_edit_stats_v2`;
TRUNCATE TABLE `huwikiquote_actor_groups_v2`;
TRUNCATE TABLE `huwikiquote_actor_v2`;
TRUNCATE TABLE `huwikisource_actor_log_stats_by_nslt_v2`;
TRUNCATE TABLE `huwikisource_actor_log_stats_v2`;
TRUNCATE TABLE `huwikisource_actor_edit_stats_by_ns_v2`;
TRUNCATE TABLE `huwikisource_actor_edit_stats_v2`;
TRUNCATE TABLE `huwikisource_actor_groups_v2`;
TRUNCATE TABLE `huwikisource_actor_v2`;
TRUNCATE TABLE `huwiki_actor_log_stats_by_nslt_v2`;
TRUNCATE TABLE `huwiki_actor_log_stats_v2`;
TRUNCATE TABLE `huwiki_actor_edit_stats_by_ns_v2`;
TRUNCATE TABLE `huwiki_actor_edit_stats_v2`;
TRUNCATE TABLE `huwiki_actor_groups_v2`;
TRUNCATE TABLE `huwiki_actor_v2`;
TRUNCATE TABLE `wiki_processed_revisions_v2`;
SET FOREIGN_KEY_CHECKS = 1;
