export const DATACACHER_REVISIONS_PROCESSED_AT_ONCE: number = 10_000;
export const DATACACHER_LOG_ENTRIES_PROCESSED_AT_ONCE: number = 10_000;
export const DATACACHER_MAXIMUM_PROCESSED_REVISIONS_IN_A_SINGLE_RUN: number = 500_000;
export const DATACACHER_MAXIMUM_LOG_ENTRIES_PROCESSED_IN_A_SINGLE_RUN: number = 500_000;
export const DATACACHER_MAXIMUM_ACTORS_PROCESSED_IN_A_SINGLE_RUN: number = 100_000;
