name: Build Package

# Run only on release branches
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: yarn

      - name: Run next.js build
        run: yarn run build

      - name: Archive next.js build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: |
            .next
            resources

      - name: Compile tools
        run: yarn run build:tools

      - name: Archive tools compilation output
        uses: actions/upload-artifact@v2
        with:
          name: tools
          path: |
            resources
            tools-out
